[build-system]
requires = ["hatchling>=1.27"]
build-backend = "hatchling.build"

[project]
name = "bee-vision-movement"
version = '0.1.0'
description = "video analysis and movement tracking on how bees see the world"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "mediapipe>=1.0.0",
    "numpy>=2.5.1",
    "opencv-python>=5.0.0.93",
]

# adding a cli entry point
[project.scripts]
bvm = "bvm.main:main"

[dependency-groups]
dev = [
    "pytest",
    "pytest-cov",
    "pyright",
    "ruff"
]

[tool.hatch.build.targets.wheel]
packages = ["src/bvm"]

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-ra --strict-config --strict-markers"

[tool.ruff]
target-version = "py312"
src = ["src", "tests"]

[tool.ruff.lint]
select = ["E4","E7","E9","F","I","UP","B"]

[tool.pyright]
include = ["src", "tests"]
pythonVersion = "3.12"
typeCheckingMode = "standard"
venvPath = "."
venv = ".venv"
